import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
const compile=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText).toString('base64');
const shared=pathToFileURL(process.cwd()+'/app/shared.ts').href;
const repayment=compile(readFileSync('app/repayment.ts','utf8').replace("'./shared'",JSON.stringify(shared)));
const payroll=compile(readFileSync('app/payroll.ts','utf8').replace("'./repayment'",JSON.stringify(repayment)));
const {validateDeductions}=await import(payroll);
const {monthCollections,dailyActivities}=await import(compile(readFileSync('app/collections.ts','utf8').replace("'./shared'",JSON.stringify(shared)).replace("'./repayment'",JSON.stringify(repayment))));
const members=[{id:'a',email:'a@example.test',name:'Same Name'},{id:'b',email:'b@example.test',name:'Same Name'}];
const loan={id:'A',member_id:'a',name:'Same Name',type:'Personal',amount:30000,total:30000,term:3,rate:0,paid:0,status:'active',start_date:'2026-01-01',created_at:'2025-12-01',late_policy:'[]',repayment_revision:0,repayment_method:'auto_deduct'};
const rows=[{loanId:'A',email:'a@example.test',amount:'100',date:'2026-01-01',reference:'PAY-A'}];
assert.equal(validateDeductions(rows,[loan],members,[])[0].status,'ready');
for(const change of [{email:'b@example.test'},{amount:'1000'},{amount:'1.001'},{amount:'-1'},{amount:'NaN'},{date:'2099-01-01'},{date:'2026-02-30'},{reference:''},{loanId:'missing'}])assert.equal(validateDeductions([{...rows[0],...change}],[loan],members,[])[0].status,'error');
assert.equal(validateDeductions(rows,[{...loan,repayment_method:'self_pay'}],members,[])[0].status,'error');
assert.ok(validateDeductions([rows[0],rows[0]],[loan],members,[]).every(r=>r.status==='error'));
const payment={id:'p',loan_id:'A',amount:10000,paid_at:'2026-01-01',name:'Same Name',reference:'PAY-A',source:'payroll',recorded_at:'2026-01-02T23:00:00Z'};
assert.equal(validateDeductions(rows,[{...loan,paid:10000}],members,[payment])[0].status,'duplicate');
assert.equal(validateDeductions([{...rows[0],amount:'101'}],[loan],members,[payment])[0].status,'error');
const january=monthCollections([{...loan,paid:15000}], [{...payment,amount:15000}], '2026-01','2026-03-01');
assert.equal(january.cash,15000);assert.equal(january.collected,10000);assert.equal(january.pending,0);
const february=monthCollections([{...loan,paid:15000}],[{...payment,amount:15000}],'2026-02','2026-03-01');assert.equal(february.cash,0);assert.equal(february.collected,5000);assert.equal(february.pending,5000);
assert.equal(dailyActivities([], [payment],[],[],'2026-01-03').length,1);
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
for(const file of ['0000_dizzy_zaladane','0001_organization_approvals','0002_member_enrollment','0003_repayment_policy','0004_late_waivers','0005_payroll_imports'])sql.exec(readFileSync('drizzle/'+file+'.sql','utf8'));
sql.prepare('INSERT INTO members(id,name,email,role) VALUES(?,?,?,?)').run('admin','Admin','admin@example.test','admin');
for(const m of members)sql.prepare('INSERT INTO members(id,name,email,role) VALUES(?,?,?,?)').run(m.id,m.name,m.email,'member');
for(const [id,member] of [['A','a'],['B','b']])sql.prepare('INSERT INTO loans(id,member_id,type,amount,term,rate,total,status,purpose,created_at,start_date) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,member,'Personal',30000,3,0,30000,'active','Test','2025-12-01','2026-01-01');
class Statement{constructor(text,params=[]){this.text=text;this.params=params}bind(...p){return new Statement(this.text,p)}async first(){return sql.prepare(this.text).get(...this.params)||null}async all(){return{results:sql.prepare(this.text).all(...this.params)}}run(){return{meta:{changes:Number(sql.prepare(this.text).run(...this.params).changes)}}}}
let conflict=false;
globalThis.__payrollDB={prepare:s=>new Statement(s),batch:async statements=>{assert.equal(statements.length,4);if(conflict){sql.exec("UPDATE loans SET repayment_revision=repayment_revision+1 WHERE id='B'");conflict=false}sql.exec('BEGIN');try{const out=statements.map(s=>s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};
const server=compile("export const db=()=>globalThis.__payrollDB;export const json=(d,s=200)=>Response.json(d,{status:s});export const string=(v,min,max)=>{if(typeof v!=='string'||v.trim().length<min||v.trim().length>max)throw Error('Invalid text');return v.trim()};");
const {importDeductions}=await import(compile(readFileSync('app/payroll-service.ts','utf8').replace("'./server'",JSON.stringify(server)).replace("'./payroll'",JSON.stringify(payroll))));
const admin={id:'admin',role:'admin'},body={filename:'payroll.xlsx',rows:[rows[0],{...rows[0],loanId:'B',email:'b@example.test',amount:'300',reference:'PAY-B'}],mode:'preview'};
assert.equal((await importDeductions({role:'member'},body)).status,403);
assert.equal((await importDeductions(admin,body)).status,200);assert.equal(sql.prepare('SELECT count(*) n FROM payments').get().n,0);
const commit={...body,mode:'commit',confirmed:true,revisions:{A:0,B:0}};
const response=await importDeductions(admin,commit);assert.equal(response.status,200);assert.equal((await response.json()).imported,2);
assert.equal(sql.prepare("SELECT status FROM loans WHERE id='B'").get().status,'completed');assert.equal(sql.prepare("SELECT paid FROM loans WHERE id='A'").get().paid,10000);
assert.equal(sql.prepare('SELECT count(*) n FROM notifications').get().n,2);
assert.equal((await (await importDeductions(admin,commit)).json()).imported,0);assert.equal(sql.prepare('SELECT count(*) n FROM payments').get().n,2);
sql.exec("DELETE FROM payments; DELETE FROM payroll_imports; UPDATE loans SET paid=0,status='active',repayment_revision=0");
const oldError=console.error;console.error=()=>{};conflict=true;assert.equal((await importDeductions(admin,commit)).status,409);console.error=oldError;
assert.equal(sql.prepare('SELECT count(*) n FROM payments').get().n,0);assert.equal(sql.prepare('SELECT count(*) n FROM payroll_imports').get().n,0);assert.equal(sql.prepare("SELECT paid FROM loans WHERE id='A'").get().paid,0);
const hundred=[];for(let i=0;i<100;i++){const id='BULK-'+i;sql.prepare('INSERT INTO loans(id,member_id,type,amount,term,rate,total,status,purpose,created_at,start_date) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,'a','Personal',30000,3,0,30000,'active','Bulk test','2025-12-01','2026-01-01');hundred.push({...rows[0],loanId:id,reference:'BULK-REF-'+i,amount:'300'})}
const bulk=await importDeductions(admin,{filename:'100-rows.xlsx',rows:hundred,mode:'commit',confirmed:true,revisions:Object.fromEntries(hundred.map(r=>[r.loanId,0]))});assert.equal(bulk.status,200);assert.equal((await bulk.json()).imported,100);assert.equal(sql.prepare("SELECT count(*) n FROM loans WHERE id LIKE 'BULK-%' AND status='completed'").get().n,100);
sql.close();delete globalThis.__payrollDB;
console.log('PASS: payroll validation, ownership, duplicate protection, preview without writes, atomic multi-loan import, full/partial payoff, concurrent rollback, cash versus schedule allocation and Manila activity dates.');
