import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const moduleUrl=source=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText).toString('base64');
const shared=pathToFileURL(process.cwd()+'/app/shared.ts').href;
const repayment=moduleUrl(readFileSync('app/repayment.ts','utf8').replace("'./shared'",JSON.stringify(shared)));
const {repaymentBalance,repaymentFields,today,nextDay}=await import(repayment);
const loan={id:'loan',member_id:'member',name:'Member',type:'Personal',amount:300000,total:300000,term:3,paid:0,start_date:'2026-01-01',created_at:'2025-12-01',status:'active',rate:0,purpose:'Test',late_policy:JSON.stringify([{effective:'0001-01-01',rateBps:300}]),repayment_revision:0};
const payment=(amount,date,interest=0)=>({id:'p',loan_id:'loan',name:'Member',amount,paid_at:date,interest_amount:interest});
assert.equal(repaymentBalance(loan,[],'2026-01-01').interestDue,0);
assert.equal(repaymentBalance(loan,[],'2026-01-11').interestDue,1000);
assert.equal(repaymentBalance(loan,[],'2026-01-31').interestDue,3000);
assert.equal(repaymentBalance({...loan,paid:50000},[payment(50000,'2026-01-11')],'2026-01-21').interestDue,1500);
assert.equal(repaymentBalance({...loan,paid:100000},[payment(100000,'2026-01-01')],'2026-01-31').interestDue,0);
assert.equal(repaymentBalance({...loan,paid:100000},[payment(100000,'2026-01-11')],'2026-01-31').interestDue,1000);
assert.equal(repaymentBalance({...loan,late_policy:'[]'},[],'2026-03-31').interestDue,0);
assert.equal(repaymentBalance({...loan,late_policy:JSON.stringify([{effective:'0001-01-01',rateBps:300},{effective:'2026-01-12',rateBps:600}])},[],'2026-01-21').interestDue,3000);
assert.equal(repaymentBalance({...loan,late_policy:JSON.stringify([{effective:'0001-01-01',rateBps:300},{effective:'2026-01-12',rateBps:0}])},[],'2026-01-21').interestDue,1000);
assert.equal(repaymentBalance({...loan,paid:300000},[payment(301000,'2026-01-11',1000)],'2026-03-31').totalDue,0);
for(const rate of [-1,101,'',NaN,Infinity,1.001])assert.throws(()=>repaymentFields({method:'auto_deduct',monthlyRate:rate}));
assert.throws(()=>repaymentFields({method:'other',monthlyRate:1}));
assert.equal(repaymentFields({method:'self_pay',monthlyRate:'2.75'}).rateBps,275);

const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
for(const file of ['0000_dizzy_zaladane','0001_organization_approvals','0002_member_enrollment','0003_repayment_policy','0004_late_waivers','0005_payroll_imports','0006_audit_trail'])sql.exec(readFileSync('drizzle/'+file+'.sql','utf8'));
sql.prepare('INSERT INTO members(id,name,email,role) VALUES(?,?,?,?)').run('member','Member','member@example.test','member');
sql.prepare('INSERT INTO members(id,name,email,role) VALUES(?,?,?,?)').run('admin','Admin','admin@example.test','admin');
sql.prepare('INSERT INTO loans(id,member_id,type,amount,term,rate,total,paid,status,purpose,created_at,start_date,late_policy) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run('loan','member','Personal',300000,3,0,300000,0,'active','Test','2025-12-01','2026-01-01',loan.late_policy);
class Statement{constructor(text,params=[]){this.text=text;this.params=params}bind(...params){return new Statement(this.text,params)}async first(){return sql.prepare(this.text).get(...this.params)||null}async all(){return{results:sql.prepare(this.text).all(...this.params)}}run(){return{meta:{changes:Number(sql.prepare(this.text).run(...this.params).changes)}}}}
globalThis.__repaymentDB={prepare:text=>new Statement(text),batch:async statements=>{sql.exec('BEGIN');try{const out=statements.map(s=>s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};
const server=moduleUrl("export const db=()=>globalThis.__repaymentDB;export const json=(d,status=200)=>Response.json(d,{status});export const string=v=>{if(typeof v!=='string'||!v.trim())throw Error('Invalid text');return v.trim()};export const notice=()=>{};");
const service=moduleUrl(readFileSync('app/repayment-service.ts','utf8').replace("'./audit'",JSON.stringify(pathToFileURL(process.cwd()+'/app/audit.ts').href)).replace("'./server'",JSON.stringify(server)).replace("'./repayment'",JSON.stringify(repayment)));
const {saveRepayment,recordRepayment,waiveInterest}=await import(service);
const admin={id:'admin',role:'admin'},member={id:'member',role:'member'};
assert.equal((await saveRepayment(member,{loanId:'loan'})).status,403);
assert.equal((await recordRepayment(member,{})).status,403);
assert.equal((await saveRepayment(admin,{loanId:'loan',revision:0,method:'self_pay',monthlyRate:2.5})).status,200);
let current=sql.prepare('SELECT * FROM loans WHERE id=?').get('loan');assert.equal(current.repayment_method,'self_pay');assert.equal(JSON.parse(current.late_policy).at(-1).effective,nextDay(today()));
assert.equal((await saveRepayment(admin,{loanId:'loan',revision:0,method:'self_pay',monthlyRate:2})).status,409);
const pay={loanId:'loan',amount:3010,date:'2026-01-11',reference:'full'};
assert.equal((await recordRepayment(admin,pay)).status,200);
current=sql.prepare('SELECT * FROM loans WHERE id=?').get('loan');assert.equal(current.paid,300000);assert.equal(current.status,'completed');assert.equal(sql.prepare('SELECT interest_amount FROM payments WHERE reference=?').get('full').interest_amount,1000);
assert.equal((await recordRepayment(admin,pay)).status,200);
assert.equal(sql.prepare('SELECT count(*) AS n FROM payments').get().n,1);
assert.equal((await recordRepayment(admin,{...pay,amount:1})).status,409);
sql.prepare("UPDATE loans SET status='active',paid=0,repayment_revision=0,late_policy=? WHERE id='loan'").run(loan.late_policy);sql.exec('DELETE FROM payments');
assert.equal((await waiveInterest(member,{})).status,403);
const before=repaymentBalance(sql.prepare("SELECT * FROM loans WHERE id='loan'").get(),[]);
assert.equal((await waiveInterest(admin,{loanId:'loan',revision:0,amount:10,reason:'Hardship support'})).status,200);
let waived=sql.prepare("SELECT * FROM loans WHERE id='loan'").get();
assert.equal(repaymentBalance(waived,[]).interestDue,before.interestDue-1000);
assert.equal(JSON.parse(waived.late_waivers)[0].reason,'Hardship support');
assert.equal(JSON.parse(waived.late_waivers)[0].adminId,'admin');
assert.equal(repaymentBalance(waived,[],'2026-01-31').interestDue,3000);
assert.equal((await waiveInterest(admin,{loanId:'loan',revision:0,amount:10,reason:'Duplicate'})).status,409);
await assert.rejects(()=>waiveInterest(admin,{loanId:'loan',revision:1,amount:999999,reason:'Too much'}));
await assert.rejects(()=>recordRepayment(admin,{loanId:'loan',amount:10,date:'2026-01-11',reference:'backdated'}));
assert.equal((await waiveInterest(admin,{loanId:'loan',revision:1,amount:(before.interestDue-1000)/100,reason:'Full hardship waiver'})).status,200);
waived=sql.prepare("SELECT * FROM loans WHERE id='loan'").get();assert.equal(repaymentBalance(waived,[]).interestDue,0);
assert.ok(repaymentBalance(waived,[],nextDay(today())).interestDue>0);
delete globalThis.__repaymentDB;
console.log('PASS: daily simple late interest, partial/on-time/late payments, rate changes, 0% disable, component allocation, admin-only settings/payments, migration, version conflicts, payoff and duplicate prevention.');

const auditCount=sql.prepare('SELECT count(*) n FROM audit_events').get().n;
assert.ok(auditCount>0,'Successful mutations create audit events');
assert.throws(()=>sql.exec("UPDATE audit_events SET action='changed'"),/cannot be edited/);
assert.throws(()=>sql.exec('DELETE FROM audit_events'),/cannot be deleted/);
assert.equal(sql.prepare('SELECT count(*) n FROM audit_events').get().n,auditCount);

sql.close();
