 'use client';
import {useEffect,useState} from 'react';
import {request} from './request';
export type AuditEvent={id:string;actor_id:string;actor_name:string;action:string;entity_id:string;created_at:string;before_json:string;after_json:string};
export function demoAudit(user:any,action:string,entity:string,before:any,after:any):AuditEvent{return{id:crypto.randomUUID(),actor_id:user.id,actor_name:user.name,action,entity_id:entity,created_at:new Date().toISOString(),before_json:JSON.stringify(before??null),after_json:JSON.stringify(after??null)}}
function changes(event:AuditEvent){
 let before:any,after:any;try{before=JSON.parse(event.before_json);after=JSON.parse(event.after_json)}catch{return[]}
 const keys=new Set([...Object.keys(before||{}),...Object.keys(after||{})]);return [...keys].filter(k=>JSON.stringify(before?.[k])!==JSON.stringify(after?.[k])).map(k=>({key:k,before:before?.[k],after:after?.[k]}));
}
const display=(v:any)=>v===undefined||v===null?'—':typeof v==='object'?JSON.stringify(v,null,2):String(v);
export function AuditTrail({preview,events:demoEvents=[]}:{preview:boolean;events?:AuditEvent[]}){
 const [search,setSearch]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[filter,setFilter]=useState({q:'',from:'',to:''}),[page,setPage]=useState(1),[reload,setReload]=useState(0),[rows,setRows]=useState<AuditEvent[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');async function load(){try{if(filter.from&&filter.to&&filter.from>filter.to)throw Error('End date must be on or after start date.');if(preview){const list=demoEvents.filter(e=>(e.actor_name+' '+e.action+' '+e.entity_id).toLowerCase().includes(filter.q.toLowerCase())&&(!filter.from||e.created_at.slice(0,10)>=filter.from)&&(!filter.to||e.created_at.slice(0,10)<=filter.to));if(active){setRows(list.slice((page-1)*50,page*50));setTotal(list.length)}}else{const r=await request('/api/audit?'+new URLSearchParams({...filter,page:String(page)}));const result:any=await r.json();if(!r.ok)throw Error(result.error||'Could not load audit history.');if(active){setRows(result.events);setTotal(result.total)}}}catch(e:any){if(active){setError(e.message);setRows([])}}finally{if(active)setLoading(false)}}load();return()=>{active=false}},[preview,demoEvents,filter,page,reload]);
 return <div className="audit-trail"><p className="notice">{preview?'Demo history lasts until reload. Try editing organization settings to see a new event.':'Permanent history of changes recorded since audit tracking was enabled. Earlier activity is not backfilled. Records cannot be edited or deleted in the app.'} Dates and times below use UTC. Monetary values in the details are stored in centavos (100 = PHP 1); rateBps uses 100 = 1%.</p><form className="panel panel-body" onSubmit={e=>{e.preventDefault();setPage(1);setFilter({q:search,from,to});setReload(n=>n+1)}}><div className="form-grid"><label className="field">Search audit history<input className="input" value={search} onChange={e=>setSearch(e.target.value)} maxLength={100} placeholder="Person, action, or record ID"/></label><label className="field">From date (UTC)<input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">To date (UTC)<input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><button className="btn primary" disabled={loading}>Search / refresh</button></form>{error&&<p role="alert" className="error">{error}</p>}{loading?<p role="status">Loading audit history…</p>:<><p className="small muted">{total} records · Page {page} of {Math.max(1,Math.ceil(total/50))}</p>{!error&&!rows.length&&<section className="panel empty"><h3>No audit events found</h3><p>New saved changes will appear here. Try a different search or date range.</p></section>}{rows.map(event=><section className="panel" key={event.id}><div className="panel-body"><div className="split"><h3>{event.action}</h3><time className="small muted">{event.created_at.replace('T',' ').replace('Z',' UTC')}</time></div><p><strong>{event.actor_name}</strong> · {event.entity_id}</p><details><summary>View change details</summary><p className="small muted">Event: {event.id}<br/>Actor ID: {event.actor_id}</p>{changes(event).map(change=><div className="audit-change" key={change.key}><strong>{change.key}</strong><div className="audit-values"><div><span className="small muted">Before</span><pre>{display(change.before)}</pre></div><div><span className="small muted">After</span><pre>{display(change.after)}</pre></div></div></div>)}</details></div></section>)}<div className="split"><button className="btn" disabled={page===1||loading} onClick={()=>setPage(n=>n-1)}>Previous</button><button className="btn" disabled={page*50>=total||loading} onClick={()=>setPage(n=>n+1)}>Next</button></div></>}</div>;
}
