'use client';
import {useState} from 'react';
import {quote,money,breakdown} from './shared';
import type {Organization} from './organization';
import {request} from './request';

export function RepaymentBreakdown({principal,total,term}:{principal:number;total:number;term:number}){
 const rows=breakdown(principal,total,term);
 return <section className="repayment-preview"><h3>Monthly repayment breakdown</h3><p className="small muted">6% annual flat interest. Dates are set after final approval. The final payment reconciles rounding.</p><div className="table-wrap"><table className="data-table mobile-cards"><thead><tr><th>Month</th><th>Principal</th><th>Interest</th><th>Payment</th><th>Principal left</th></tr></thead><tbody>{rows.map(r=><tr key={r.number}><td data-label="Month">{r.number}</td><td data-label="Principal">{money(r.principal)}</td><td data-label="Interest">{money(r.interest)}</td><td data-label="Payment"><strong>{money(r.amount)}</strong></td><td data-label="Principal left">{money(r.balance)}</td></tr>)}</tbody><tfoot><tr><td data-label="Summary">Total</td><td data-label="Principal">{money(principal)}</td><td data-label="Interest">{money(total-principal)}</td><td data-label="Repayment">{money(total)}</td><td data-label="Balance">{money(0)}</td></tr></tfoot></table></div></section>;
}
export async function uploadAttachment(original:File){
 if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(original.type)||!original.size||original.size>10*1024*1024)throw Error('Choose a PDF, JPEG, PNG or WebP between 1 byte and 10 MB.');
 let file=original;
 if(file.type.startsWith('image/')&&typeof createImageBitmap==='function'){
 const img=await createImageBitmap(file);try{const scale=Math.min(1,2000/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');if(ctx){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',.88));if(blob&&blob.size<file.size)file=new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg'})}}finally{img.close()}}
 const form=new FormData();form.append('file',file);const response=await request('/api/documents',{method:'POST',body:form});const result=await response.json() as any;if(!response.ok)throw Error(result.error||'Upload failed. Retry the attachment.');return{id:result.id,name:file.name};
}
export function LoanApplication({organization,documents,memberId,preview,busy,offline,onSubmit,onCancel}:{organization:Organization;documents:any[];memberId:string;preview:boolean;busy:boolean;offline:boolean;onSubmit:(body:any)=>Promise<boolean>;onCancel:()=>void}){
 const available=organization.loanTypes.filter(t=>t.active);const [typeId,setTypeId]=useState(available[0]?.id||''),[amount,setAmount]=useState('25000'),[term,setTerm]=useState('12'),[attachments,setAttachments]=useState<{id:string;name:string}[]>([]),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 const type=available.find(t=>t.id===typeId);let estimate:ReturnType<typeof quote>|null=null;try{estimate=quote(Number(amount),Number(term))}catch{}
 async function attach(e:React.ChangeEvent<HTMLInputElement>){const input=e.currentTarget,files=Array.from(input.files||[]);input.value='';if(files.length+attachments.length>5){setError('Attach no more than five documents.');return}setError('');setUploading(true);try{for(const file of files){if(!file.size||file.size>10*1024*1024||!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))throw Error('Choose a PDF, JPEG, PNG or WebP under 10 MB.');const doc=preview?{id:'demo-'+crypto.randomUUID(),name:file.name}:await uploadAttachment(file);setAttachments(current=>[...current,doc])}}catch(e:any){setError(e.message)}finally{setUploading(false)}}
 return <form onSubmit={async e=>{e.preventDefault();if(uploading||busy||!estimate||!type)return;const fields=new FormData(e.currentTarget);await onSubmit({typeId,amount,term,purpose:fields.get('purpose'),documentIds:preview?[]:attachments.map(d=>d.id),demoAttachments:preview?attachments:undefined,organizationRevision:organization.revision})}}>
 <p className="small muted">Review your repayments and approval steps before sending your application.</p>
 <div className="form-grid" style={{marginTop:20}}><label className="field full">Loan type<select className="input" required value={typeId} onChange={e=>setTypeId(e.target.value)}>{available.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="field">Requested amount (₱)<input className="input" type="number" inputMode="decimal" min="1000" max="500000" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/><small>₱1,000 to ₱500,000</small></label><label className="field">Repayment period<select className="input" value={term} onChange={e=>setTerm(e.target.value)}>{[3,6,12,18,24].map(t=><option key={t} value={t}>{t} months</option>)}</select></label><label className="field full">Purpose<textarea className="input" name="purpose" required minLength={10} maxLength={1000} rows={3} placeholder="What will you use the loan for?"/></label></div>
 <section className="application-section"><h3>Supporting documents <span className="small muted">Optional · up to 5</span></h3><p className="small muted">PDF, JPEG, PNG or WebP · 10 MB per file. {preview?'Demo: files stay on your device and are not uploaded.':'Files upload securely now and remain in Documents if you cancel.'}</p><div className="attachment-controls"><label className="btn">Choose files<input type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp" onChange={attach} disabled={uploading||busy||offline}/></label><label className="btn">Take a photo<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={attach} disabled={uploading||busy||offline}/></label></div>
 {documents.some(d=>d.member_id===memberId&&!d.loan_id&&!attachments.some(a=>a.id===d.id))&&<label className="field">Or attach an existing document<select className="input" value="" disabled={uploading||busy||attachments.length>=5} onChange={e=>{const doc=documents.find(d=>d.id===e.target.value);if(doc)setAttachments([...attachments,{id:doc.id,name:doc.name}])}}><option value="">Select a document</option>{documents.filter(d=>d.member_id===memberId&&!d.loan_id&&!attachments.some(a=>a.id===d.id)).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}
 {attachments.map(a=><div className="attachment-item" key={a.id}><span>{a.name}</span><button type="button" className="text-link" disabled={busy||uploading} aria-label={'Remove '+a.name} onClick={()=>setAttachments(attachments.filter(d=>d.id!==a.id))}>Remove</button></div>)}{uploading&&<p role="status">Uploading document…</p>}{error&&<p className="error" role="alert">{error}</p>}</section>
 {estimate?<><div className="estimate"><div>Estimated monthly payment<p className="small muted">Total interest {money(estimate.interest)} · Total repayment {money(estimate.total)}</p></div><strong>{money(estimate.monthly)}</strong></div><RepaymentBreakdown principal={estimate.principal} total={estimate.total} term={Number(term)}/></>:<p className="error">Enter a valid amount to preview your repayments.</p>}
 <section className="application-section"><h3>Your approval sequence</h3><p className="small muted">Each role reviews in order. Your loan starts only after the final approval.</p><ol className="approval-sequence">{type?.steps.map((id,i)=><li key={id}><span className="step-number">{i+1}</span><span>{organization.roles.find(r=>r.id===id)?.name||'Unconfigured role'}</span></li>)}</ol>{!type&&<p className="error">No loan types are currently available. Contact your administrator.</p>}</section>
 <p className="small muted">All enrolled members may apply, including administrators and approvers. You cannot approve your own loan. If your approval route needs another reviewer, your application will stay pending until an administrator assigns one.</p><label className="confirmation"><input type="checkbox" required/>I have reviewed the monthly breakdown and confirm my application details.</label><div className="modal-actions"><button type="button" className="btn" disabled={uploading||busy} onClick={onCancel}>Cancel</button><button className="btn primary" disabled={busy||uploading||offline||!estimate||!type}>{busy?'Submitting…':preview?'Try demo submission':'Submit application'}</button></div>
 </form>;
}

