'use client';
import {useEffect,useRef,useState} from 'react';
import {validateOrganization,type Organization,type OrgRole,type LoanType} from './organization';
import {Pagination} from './admin-workspace';
import {memberFields} from './member-enrollment';
type Member={id:string;name:string;email:string;phone?:string;department?:string;enrollment_status?:string};
type Editor={kind:'enroll'}|{kind:'member'|'assignment';member:Member}|{kind:'role';role:OrgRole}|{kind:'loan';loan:LoanType};
export function OrganizationEditor({value,members,busy,preview,onSave,onMemberSave,onOpenLoans,initialSection='Members'}:{onOpenLoans?:(id:string)=>void;initialSection?:string;value:Organization;members:Member[];busy:boolean;preview:boolean;onSave:(value:Organization)=>Promise<boolean>;onMemberSave:(value:any)=>Promise<boolean>}){
 const [search,setSearch]=useState(''),[editor,setEditor]=useState<Editor|null>(null),[error,setError]=useState(''),[company,setCompany]=useState(value.name),[companyOpen,setCompanyOpen]=useState(false);
 const [directoryPage,setDirectoryPage]=useState(1);useEffect(()=>setDirectoryPage(1),[search]);
 const panel=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(editor){panel.current?.scrollIntoView({block:'start',behavior:'smooth'});panel.current?.querySelector<HTMLInputElement>('input')?.focus()}},[editor]);
 useEffect(()=>setCompany(value.name),[value.name]);
 const roleName=(id:string)=>value.roles.find(r=>r.id===id)?.name||'Unknown role';
 const assigned=(id:string)=>value.assignments.filter(a=>a.member_id===id).map(a=>roleName(a.role_id));
 function open(next:Editor){setError('');setEditor(next)}
 async function save(next:Organization){try{setError('');validateOrganization(next,members.map(m=>m.id),value.roles.map(r=>r.id));const ok=await onSave(next);if(ok)setEditor(null);return ok}catch(e:any){setError(e.message);return false}}
 const filtered=members.filter(m=>(m.name+' '+m.email+' '+m.department+' '+assigned(m.id).join(' ')).toLowerCase().includes(search.toLowerCase()));
 return <div className="org-hub">
 <section className="panel"><div className="panel-body">{!companyOpen?<div className="split"><div><p className="small muted">Company / union</p><h3>{value.name}</h3></div><button className="btn" onClick={()=>setCompanyOpen(true)}>Edit company name</button></div>:<form className="company-form" onSubmit={async e=>{e.preventDefault();if(await save({...value,name:company}))setCompanyOpen(false)}}><label className="field">Company or union name<input className="input" value={company} onChange={e=>setCompany(e.target.value)} required maxLength={100}/></label><button className="btn" disabled={busy||company.trim()===value.name}>Save name</button><button type="button" className="btn" onClick={()=>{setCompany(value.name);setCompanyOpen(false)}}>Cancel</button></form>}</div></section>
 <nav className="org-tabs" aria-label="Organization sections">{[['org-members','Members',members.length],['org-roles','Roles',value.roles.length],['org-approvals','Loan approvals',value.loanTypes.length],['org-defaults','Loan defaults','']].map(([id,label,count])=><button key={id} type="button" onClick={()=>document.getElementById(String(id))?.scrollIntoView({behavior:'smooth',block:'start'})}>{label} <span>{count}</span></button>)}</nav>
 <p className="small muted">Manage your company, enrolled members, roles, and loan approvals on this page. Choose an Edit button, make your changes, then save.</p>
 {error&&<p className="error" role="alert">{error}</p>}
 {editor&&<div className="panel org-edit-panel" ref={panel}><div className="panel-head"><h2>{editor.kind==='enroll'?'Enroll a member':editor.kind==='member'?'Edit member details':editor.kind==='assignment'?'Assign roles to '+editor.member.name:editor.kind==='role'?'Role details':'Loan approval settings'}</h2><button type="button" className="btn" disabled={busy} onClick={()=>setEditor(null)}>Cancel</button></div><div className="panel-body">
 {(editor.kind==='enroll'||editor.kind==='member')&&<form key={editor.kind==='member'?editor.member.id:'new'} onSubmit={async e=>{e.preventDefault();try{setError('');const fields=memberFields(Object.fromEntries(new FormData(e.currentTarget)));if(await onMemberSave({...fields,memberId:editor.kind==='member'?editor.member.id:undefined}))setEditor(null)}catch(e:any){setError(e.message)}}}><div className="form-grid"><label className="field">Full name<input className="input" name="name" required maxLength={100} defaultValue={editor.kind==='member'?editor.member.name:''}/></label><label className="field">Personal email<input className="input" name="email" type="email" required maxLength={254} defaultValue={editor.kind==='member'?editor.member.email:''} readOnly={editor.kind==='member'&&editor.member.enrollment_status==='active'} placeholder="name@gmail.com"/><small>{editor.kind==='member'&&editor.member.enrollment_status==='active'?'Email is locked after first sign-in to protect this account.':'The member must use this same email when signing in.'}</small></label><label className="field">Department or team<input className="input" name="department" maxLength={100} defaultValue={editor.kind==='member'?editor.member.department:''} placeholder="Optional"/></label><label className="field">Phone number<input className="input" name="phone" type="tel" maxLength={30} defaultValue={editor.kind==='member'?editor.member.phone:''} placeholder="Optional"/></label></div>{editor.kind==='enroll'&&<p className="notice">Enrollment adds this person to your directory. Assign roles after saving. No invitation email is sent.</p>}<button className="btn primary" disabled={busy}>{busy?'Saving…':editor.kind==='enroll'?'Enroll member':'Save member details'}</button></form>}
 {editor.kind==='assignment'&&<MemberRoleForm key={editor.member.id} member={editor.member} organization={value} busy={busy} onSave={ids=>save({...value,assignments:[...value.assignments.filter(a=>a.member_id!==editor.member.id),...ids.map(role_id=>({role_id,member_id:editor.member.id}))]})}/>}

 {editor.kind==='role'&&<form key={editor.role.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const role={...editor.role,name:String(f.get('name')),parent_id:String(f.get('parent_id')||'')||null};save({...value,roles:value.roles.some(r=>r.id===role.id)?value.roles.map(r=>r.id===role.id?role:r):[...value.roles,role]})}}><div className="form-grid"><label className="field">Role name<input className="input" name="name" required maxLength={100} defaultValue={editor.role.name} placeholder="For example: Admin Staff or President"/></label><label className="field">Reports to<select className="input" name="parent_id" defaultValue={editor.role.parent_id||''}><option value="">No parent / top-level role</option>{value.roles.filter(r=>r.id!==editor.role.id).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div><p className="small muted" style={{marginBottom:16}}>After saving, use Members & role assignments → Assign roles to choose who holds this role.</p><button className="btn primary" disabled={busy}>{busy?'Saving…':'Save role'}</button></form>}
 {editor.kind==='loan'&&<LoanRouteForm key={editor.loan.id} loan={editor.loan} organization={value} busy={busy} onSave={loan=>save({...value,loanTypes:value.loanTypes.some(t=>t.id===loan.id)?value.loanTypes.map(t=>t.id===loan.id?loan:t):[...value.loanTypes,loan]})}/>}
 </div></div>}
 <section id="org-members" className="org-settings-section"><div className="org-section-heading"><div><h2>Members &amp; role assignments</h2><p className="small muted">Enroll a personal email first, then select roles for that person.</p></div><button className="btn primary" disabled={busy} onClick={()=>open({kind:'enroll'})}>+ Enroll member</button></div><label className="field org-search">Search members<input className="input" type="search" placeholder="Search name, email, team, or role" value={search} onChange={e=>setSearch(e.target.value)}/></label><section className="panel"><div className="table-wrap"><table className="data-table mobile-cards org-members"><thead><tr><th>Member</th><th>Personal email</th><th>Roles</th><th>Enrollment</th><th>Actions</th></tr></thead><tbody>{filtered.slice((directoryPage-1)*15,directoryPage*15).map(m=><tr key={m.id}><td data-label="Member"><div><strong>{m.name}</strong><p className="small muted">{m.department||'No team set'}</p></div></td><td data-label="Personal email">{m.email}</td><td data-label="Roles"><div className="role-chips">{assigned(m.id).length?assigned(m.id).map(name=><span className="badge" key={name}>{name}</span>):<span className="muted">No roles assigned</span>}</div></td><td data-label="Enrollment"><span className={'pill '+(m.enrollment_status==='pending'?'pending':'')}>{m.enrollment_status==='pending'?'Awaiting first sign-in':'Active'}</span></td><td data-label="Actions"><div className="member-row-actions">{onOpenLoans&&<button className="btn" onClick={()=>onOpenLoans(m.id)}>Open loans</button>}<button className="text-link" disabled={busy} aria-label={'Edit details for '+m.name} onClick={()=>open({kind:'member',member:m})}>Edit details</button><button className="btn" disabled={busy} aria-label={'Assign roles to '+m.name} onClick={()=>open({kind:'assignment',member:m})}>Assign roles</button></div></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="empty"><h3>{members.length?'No members match your search':'No members enrolled yet'}</h3><p>{members.length?'Try a different name or email.':'Use Enroll member to add a person by their personal email.'}</p></div>}<Pagination total={filtered.length} page={directoryPage} onChange={setDirectoryPage}/></section></section>
 <section id="org-roles" className="org-settings-section"><div className="org-section-heading"><div><h2>Organization roles</h2><p className="small muted">Define roles here. These become the dropdown options for members and approvers.</p></div><button className="btn primary" disabled={busy} onClick={()=>open({kind:'role',role:{id:crypto.randomUUID(),name:'',parent_id:null}})}>+ Create role</button></div><div className="org-card-grid">{value.roles.map(r=>{const people=value.assignments.filter(a=>a.role_id===r.id).map(a=>members.find(m=>m.id===a.member_id)).filter(Boolean) as Member[];return <section className="panel" key={r.id}><div className="panel-body"><div className="split"><h3>{r.name}</h3><button className="btn" disabled={busy} aria-label={'Edit role '+r.name} onClick={()=>open({kind:'role',role:r})}>Edit</button></div><p className="small muted">{r.parent_id?'Reports to '+roleName(r.parent_id):'Top-level role'}</p><p className="org-people-title">{people.length} assigned {people.length===1?'member':'members'}</p>{people.length?people.map(m=><div className="org-person" key={m.id}><strong>{m.name}</strong><span>{m.email}</span></div>):<p className="small muted">No one assigned yet. Assign enrolled members from the Members section.</p>}</div></section>})}{!value.roles.length&&<p className="empty">Create your first role to begin assigning responsibilities.</p>}</div></section>
 <section id="org-approvals" className="org-settings-section"><div className="org-section-heading"><div><h2>Loan types &amp; approval order</h2><p className="small muted">Select approvers from your organization roles for each loan type.</p></div><button className="btn primary" disabled={busy} onClick={()=>open({kind:'loan',loan:{id:crypto.randomUUID(),name:'',active:0,steps:[]}})}>+ Add loan type</button></div><div className="org-card-grid">{value.loanTypes.map(t=><section className="panel" key={t.id}><div className="panel-body"><div className="split"><h3>{t.name}</h3><span className={'pill '+(t.active?'':'pending')}>{t.active?'Enabled':'Disabled'}</span></div><ol className="approval-sequence">{t.steps.map((r,i)=><li key={r}><span className="step-number">{i+1}</span>{roleName(r)}</li>)}</ol>{!t.steps.length&&<p className="small muted">No approval steps configured.</p>}<button className="btn" disabled={busy} onClick={()=>open({kind:'loan',loan:t})} aria-label={'Edit approval route for '+t.name}>Edit approval route</button></div></section>)}</div></section>
 <section id="org-defaults" className="panel org-settings-section"><form className="panel-body" onSubmit={e=>{e.preventDefault();const rate=Number(new FormData(e.currentTarget).get('rate'));save({...value,default_late_rate_bps:Math.round(rate*100)})}}><h2>Loan defaults</h2><p className="small muted">New applications use this rate. Existing loans keep their saved terms. Use Member loans to edit a loan or waive charges.</p><label className="field">Default monthly late-payment interest (%)<input className="input" key={value.default_late_rate_bps??300} name="rate" type="number" min="0" max="100" step="0.01" required defaultValue={(value.default_late_rate_bps??300)/100}/></label><button className="btn primary" disabled={busy}>Save default rate</button></form></section>
 </div>;
}
function LoanRouteForm({loan,organization,busy,onSave}:{loan:LoanType;organization:Organization;busy:boolean;onSave:(loan:LoanType)=>Promise<boolean>}){
 const [steps,setSteps]=useState([...loan.steps]);
 return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({...loan,name:String(f.get('name')),active:f.get('active')?1:0,steps})}}><label className="field">Loan type name<input className="input" name="name" required maxLength={100} defaultValue={loan.name}/></label><label className="confirmation"><input type="checkbox" name="active" defaultChecked={!!loan.active}/>Accept new applications for this loan type</label><p className="small muted">Add approval roles in order. Existing applications keep their original sequence.</p><ol className="approval-sequence route-editor">{steps.map((role,i)=><li key={i}><span className="step-number">{i+1}</span><label className="field">Approver {i+1}<select className="input" value={role} onChange={e=>setSteps(steps.map((r,j)=>i===j?e.target.value:r))}>{organization.roles.map(r=><option key={r.id} value={r.id} disabled={steps.includes(r.id)&&r.id!==role}>{r.name}</option>)}</select></label><div className="step-actions"><button type="button" aria-label={'Move approver '+(i+1)+' up'} disabled={i===0} onClick={()=>{const next=[...steps];[next[i-1],next[i]]=[next[i],next[i-1]];setSteps(next)}}>↑</button><button type="button" aria-label={'Move approver '+(i+1)+' down'} disabled={i===steps.length-1} onClick={()=>{const next=[...steps];[next[i+1],next[i]]=[next[i],next[i+1]];setSteps(next)}}>↓</button><button type="button" aria-label={'Remove approver '+(i+1)} onClick={()=>setSteps(steps.filter((_,j)=>j!==i))}>Remove</button></div></li>)}</ol><button className="btn" type="button" disabled={steps.length>=20||!organization.roles.some(r=>!steps.includes(r.id))} onClick={()=>setSteps([...steps,organization.roles.find(r=>!steps.includes(r.id))!.id])}>+ Add approval step</button><div className="modal-actions"><button className="btn primary" disabled={busy}>{busy?'Saving…':'Save approval route'}</button></div></form>;
}

function MemberRoleForm({member,organization,busy,onSave}:{member:Member;organization:Organization;busy:boolean;onSave:(ids:string[])=>Promise<boolean>}){
 const [ids,setIds]=useState(organization.assignments.filter(a=>a.member_id===member.id).map(a=>a.role_id));
 return <form onSubmit={e=>{e.preventDefault();onSave(ids.filter(Boolean))}}><p className="small muted">{member.email} · Choose this member’s roles from the dropdowns.</p>{ids.map((id,index)=><div className="member-role-row" key={index}><label className="field">Role {index+1}<select className="input" required value={id} disabled={busy} onChange={e=>setIds(ids.map((v,i)=>i===index?e.target.value:v))}><option value="">Select a role</option>{organization.roles.map(r=><option key={r.id} value={r.id} disabled={ids.includes(r.id)&&r.id!==id}>{r.name}</option>)}</select></label><button className="btn" type="button" disabled={busy} aria-label={'Remove role '+(index+1)} onClick={()=>setIds(ids.filter((_,i)=>i!==index))}>Remove</button></div>)}{!ids.length&&<p className="notice">No approval roles assigned. This member can still apply for a loan.</p>}<button className="btn" type="button" disabled={busy||ids.length>=organization.roles.length} onClick={()=>setIds([...ids,''])}>+ Add role</button><p className="small muted">Create additional roles in Organization roles below. Administrator access is managed separately.</p><div className="modal-actions"><button className="btn primary" disabled={busy}>{busy?'Saving…':'Save member roles'}</button></div></form>;
}
