'use client';
import {useState} from 'react';
import {validateOrganization,type Organization} from './organization';
export function OrganizationEditor({value,members,busy,preview,onSave}:{value:Organization;members:any[];busy:boolean;preview:boolean;onSave:(value:Organization)=>Promise<boolean>}){
 const [draft,setDraft]=useState<Organization>(()=>structuredClone(value)),[error,setError]=useState('');
 function roleChange(id:string,changes:any){setDraft({...draft,roles:draft.roles.map(r=>r.id===id?{...r,...changes}:r)})}
 function typeChange(id:string,changes:any){setDraft({...draft,loanTypes:draft.loanTypes.map(t=>t.id===id?{...t,...changes}:t)})}
 return <form onSubmit={async e=>{e.preventDefault();setError('');try{const valid=validateOrganization(draft,members.map(m=>m.id),value.roles.map(r=>r.id));await onSave(valid)}catch(e:any){setError(e.message)}}} className="org-editor">
 <section className="panel"><div className="panel-head"><h2>Company organization</h2></div><div className="panel-body"><label className="field">Company or union name<input className="input" required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><p className="small muted">Create roles, organize reporting lines, and assign signed-in members. Organization roles grant approval access only; they do not grant administrator access.</p></div></section>
 <section className="panel"><div className="panel-head"><h2>Roles & reporting lines</h2><button className="btn" type="button" onClick={()=>setDraft({...draft,roles:[...draft.roles,{id:crypto.randomUUID(),name:'',parent_id:null}]})}>Add role</button></div><div className="panel-body stack">{draft.roles.map(r=><div className="organization-role" key={r.id}><div className="form-grid"><label className="field">Role name<input className="input" required value={r.name} maxLength={100} onChange={e=>roleChange(r.id,{name:e.target.value})}/></label><label className="field">Reports to<select className="input" value={r.parent_id||''} onChange={e=>roleChange(r.id,{parent_id:e.target.value||null})}><option value="">Top-level role</option>{draft.roles.filter(x=>x.id!==r.id).map(x=><option key={x.id} value={x.id}>{x.name||'Unnamed role'}</option>)}</select></label></div><fieldset className="role-members"><legend>Members assigned to {r.name||'this role'}</legend>{members.map(m=><label key={m.id} className="confirmation"><input type="checkbox" checked={draft.assignments.some(a=>a.role_id===r.id&&a.member_id===m.id)} onChange={e=>setDraft({...draft,assignments:e.target.checked?[...draft.assignments,{member_id:m.id,role_id:r.id}]:draft.assignments.filter(a=>!(a.member_id===m.id&&a.role_id===r.id))})}/><span>{m.name}<small className="muted"> {m.email}</small></span></label>)}{!members.length&&<p className="small muted">Members appear here after their first sign-in.</p>}</fieldset></div>)}</div></section>
 <section className="panel"><div className="panel-head"><h2>Loan types & approval steps</h2><button className="btn" type="button" onClick={()=>setDraft({...draft,loanTypes:[...draft.loanTypes,{id:crypto.randomUUID(),name:'',active:0,steps:draft.roles[0]?[draft.roles[0].id]:[]}]})}>Add loan type</button></div><div className="panel-body stack"><p className="small muted">Choose any ordered sequence of 1–20 distinct roles. One assigned person approves each step. Applicants cannot approve their own requests. Changes apply to new applications; current role assignments determine who can act on pending steps.</p>{draft.loanTypes.map(t=><div className="organization-role" key={t.id}><label className="field">Loan type name<input className="input" required value={t.name} maxLength={100} onChange={e=>typeChange(t.id,{name:e.target.value})}/></label><label className="confirmation"><input type="checkbox" checked={!!t.active} onChange={e=>typeChange(t.id,{active:e.target.checked?1:0})}/>Available for applications</label><ol className="approval-sequence">{t.steps.map((role,i)=><li key={i}><span className="step-number">{i+1}</span><label className="field"><span className="small">Approver {i+1}</span><select className="input" required value={role} onChange={e=>typeChange(t.id,{steps:t.steps.map((r,j)=>j===i?e.target.value:r)})}>{draft.roles.map(r=><option key={r.id} value={r.id}>{r.name||'Unnamed role'}</option>)}</select></label><div className="step-actions"><button type="button" aria-label={'Move step '+(i+1)+' up for '+t.name} disabled={i===0} onClick={()=>{const steps=[...t.steps];[steps[i-1],steps[i]]=[steps[i],steps[i-1]];typeChange(t.id,{steps})}}>↑</button><button type="button" aria-label={'Move step '+(i+1)+' down for '+t.name} disabled={i===t.steps.length-1} onClick={()=>{const steps=[...t.steps];[steps[i],steps[i+1]]=[steps[i+1],steps[i]];typeChange(t.id,{steps})}}>↓</button><button type="button" aria-label={'Remove step '+(i+1)+' for '+t.name} onClick={()=>typeChange(t.id,{steps:t.steps.filter((_,j)=>j!==i)})}>Remove</button></div></li>)}</ol><button className="btn" type="button" disabled={t.steps.length>=20||!draft.roles.some(r=>!t.steps.includes(r.id))} onClick={()=>typeChange(t.id,{steps:[...t.steps,draft.roles.find(r=>!t.steps.includes(r.id))!.id]})}>Add approval step</button></div>)}</div></section>
 {error&&<p role="alert" className="error">{error}</p>}<div className="org-save"><p className="small muted">{preview?'Demo changes last until you reload this page.':'Save updates the organization and approval routes together.'}</p><button className="btn primary" disabled={busy}>{busy?'Saving…':preview?'Try organization settings':'Save organization'}</button></div>
 </form>;
}
