'use client';
import {useState} from 'react';
import {Upload,Download,CheckCircle2,FileSpreadsheet} from 'lucide-react';
import {money,type Loan,type Payment} from './shared';
import {repaymentBalance,today} from './repayment';
import {readPayrollWorkbook,downloadWorkbook} from './payroll-excel';
import type {DeductionRow,DeductionResult} from './payroll';
import {Pagination} from './admin-workspace';
export function PayrollImport({loans,members,imports,payments,preview,onImport}:{loans:Loan[];members:any[];imports:any[];payments:Payment[];preview:boolean;onImport:(body:any)=>Promise<any>}){
 const [rows,setRows]=useState<DeductionRow[]>([]),[result,setResult]=useState<DeductionResult[]>([]),[filename,setFilename]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[confirmed,setConfirmed]=useState(false),[page,setPage]=useState(1),[historyPage,setHistoryPage]=useState(1);
 const ready=result.filter(r=>r.status==='ready'),invalid=result.filter(r=>r.status==='error'),duplicates=result.filter(r=>r.status==='duplicate');
 async function previewRows(next:DeductionRow[],name:string){setResult([]);setSuccess('');setConfirmed(false);setPage(1);setRows(next);setFilename(name);const data=await onImport({mode:'preview',filename:name,rows:next});setResult(data.rows)}
 async function choose(file?:File){if(!file)return;setBusy(true);setError('');setResult([]);setRows([]);setSuccess('');try{await previewRows(await readPayrollWorkbook(file),file.name)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function dummy(){return loans.filter(l=>l.is_demo&&l.status==='active'&&l.repayment_method!=='self_pay').slice(0,3).map((l,i)=>({row:i+2,loanId:l.id,email:members.find(m=>m.id===l.member_id)?.email||'',amount:((i===2?repaymentBalance(l,payments).totalDue:Math.min(Math.floor(l.total/l.term),repaymentBalance(l,payments).totalDue))/100).toFixed(2),date:today(),reference:`DEMO-PAYROLL-${today()}-${l.id}`}))}
 return <div className="admin-workspace"><section className="payroll-intro"><FileSpreadsheet size={28}/><div><h2>Record salary deductions from Excel</h2><p>Upload payroll’s confirmed deductions, review the matches, then record all valid payments together. There is no payroll-system integration.</p></div></section><section className="panel"><div className="panel-body"><ol className="import-steps"><li><strong>1. Prepare the file</strong><span>One row per loan, up to 100 rows. Use exact loan IDs and personal emails.</span></li><li><strong>2. Review the preview</strong><span>Check each member, amount and date. Fix errors in Excel and upload again.</span></li><li><strong>3. Confirm deductions</strong><span>Balances and schedules update automatically; only a full payoff closes a loan.</span></li></ol><div className="row-actions"><button className="btn" onClick={()=>downloadWorkbook([],'payroll-deductions-template.xlsx')}><Download size={16}/>Download Excel template</button>{preview&&<button className="btn" onClick={()=>downloadWorkbook(dummy(),'dummy-payroll-deductions.xlsx')}><Download size={16}/>Download dummy deductions</button>}<label className={'btn primary '+(busy?'disabled':'')}><Upload size={16}/>{busy?'Processing…':'Upload Excel deductions'}<input aria-label="Upload Excel deductions" type="file" accept=".xlsx" disabled={busy} onChange={e=>{choose(e.target.files?.[0]);e.target.value=''}} style={{position:'absolute',width:1,height:1,opacity:0}}/></label></div><p className="small muted" style={{marginTop:14}}>Columns: Loan ID · Member Email · Amount PHP · Payment Date (YYYY-MM-DD) · Reference. Use a unique payroll reference per deduction, and reuse it if retrying. .xlsx only, up to 2 MB. Paste values; formulas are rejected.</p>{preview&&<p className="notice">Dummy mode: changes stay in this browser session. No real deductions are submitted. The dummy file includes partial payments and one full payoff.</p>}</div></section>{busy&&<p role="status">Validating and processing deductions…</p>}{error&&<div className="error" role="alert">{error}{rows.length>0&&<button className="btn" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await previewRows(rows,filename)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Preview again</button>}</div>}{success&&<div className="import-success" role="status"><CheckCircle2 size={21}/>{success}</div>}
 {result.length>0&&<section className="panel"><div className="panel-head"><div><h2>{success?'Import result':'Review deductions'}</h2><p className="small muted">{filename}</p></div><strong>{money(ready.reduce((s,r)=>s+r.amountCents,0))}</strong></div><div className="directory-summary panel-body"><span>{ready.length} {success?'recorded':'ready'}</span><span>{duplicates.length} already recorded</span><span>{invalid.length} errors</span></div><div className="table-wrap"><table className="data-table mobile-cards payroll-table"><thead><tr><th>Row / member</th><th>Loan / reference</th><th>Deduction</th><th>Date</th><th>Result</th></tr></thead><tbody>{result.slice((page-1)*15,page*15).map(r=><tr key={r.row}><td data-label="Member"><div><strong>{r.row}. {r.name||'Unmatched member'}</strong><small>{r.email}</small></div></td><td data-label="Loan"><div>{r.loanId}<small>{r.reference}</small></div></td><td data-label="Deduction"><div><strong>{money(r.amountCents)}</strong>{r.status==='ready'&&<small>Remaining: {money(r.remaining)}</small>}</div></td><td data-label="Payment date">{r.date}</td><td data-label="Result"><div><span className={'pill '+(r.status==='error'?'rejected':r.status==='duplicate'?'pending':'active')}>{r.status==='ready'?(success?'Recorded':'Ready'):r.status==='duplicate'?'Skipped':'Fix required'}</span><small>{r.message}</small></div></td></tr>)}</tbody></table></div><Pagination total={result.length} page={page} onChange={setPage}/>{!success&&<div className="panel-body">{invalid.length>0?<p className="error">No payments will be recorded until every error is fixed.</p>:<><label className="confirmation"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy||!ready.length}/>I confirm these deductions were received through payroll and the members, amounts and dates are correct.</label><button className="btn primary" disabled={busy||!confirmed||!ready.length} onClick={async()=>{setBusy(true);setError('');try{const data=await onImport({mode:'commit',confirmed:true,filename,rows,revisions:Object.fromEntries(ready.map(r=>[r.loanId,r.revision]))});setSuccess(data.message);setResult(data.rows);setConfirmed(false)}catch(e:any){setError(e.message);setConfirmed(false)}finally{setBusy(false)}}}>{busy?'Recording…':`Record ${ready.length} deductions`}</button></>}</div>}</section>}
 <section className="panel"><div className="panel-head"><h2>Import history</h2><span className="muted small">{preview?'This demo session':'Latest 100 imports'}</span></div>{imports.length?<><div className="table-wrap"><table className="data-table mobile-cards payroll-table"><thead><tr><th>File</th><th>Recorded</th><th>Deductions</th><th>Total</th><th>By</th></tr></thead><tbody>{imports.slice((historyPage-1)*15,historyPage*15).map(i=><tr key={i.id}><td data-label="File"><div>{i.filename}<small>{i.id}</small></div></td><td data-label="Recorded">{new Date(i.created_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</td><td data-label="Deductions">{i.row_count} recorded · {i.skipped} skipped</td><td data-label="Total">{money(i.total)}</td><td data-label="By">{i.recorded_by_name}</td></tr>)}</tbody></table></div><Pagination total={imports.length} page={historyPage} onChange={setHistoryPage}/></>:<div className="empty"><FileSpreadsheet size={28}/><h3>No payroll imports yet</h3><p>Completed uploads will appear here with the administrator and totals.</p></div>}</section></div>;
}
