export type Loan={id:string;member_id:string;name:string;type:string;amount:number;term:number;rate:number;total:number;paid:number;status:string;created_at:string;start_date:string;purpose:string;is_demo?:number;repayment_method?:string;late_policy?:string;late_waivers?:string;repayment_revision?:number;late_interest_due?:number;late_interest_accrued?:number;balance_due?:number;balance_as_of?:string};
export type Payment={id:string;loan_id:string;amount:number;paid_at:string;name:string;interest_amount?:number;reference?:string;source?:string;import_id?:string;recorded_at?:string};
export function money(cents:number,symbol=true){return (symbol?'₱':'')+((cents||0)/100).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}
export function quote(pesos:number,term:number){if(!Number.isFinite(pesos)||pesos<1000||pesos>500000||![3,6,12,18,24].includes(term))throw Error('Choose ₱1,000–₱500,000 and a supported repayment term.');const principal=Math.round(pesos*100);if(Math.abs(pesos*100-principal)>.00001)throw Error('Enter an amount with at most two decimal places.');const interest=Math.round(principal*.06*term/12);const total=principal+interest;return{principal,interest,total,monthly:Math.floor(total/term),rows:breakdown(principal,total,term)}}
// Keep the existing equal-payment convention. Allocate interest proportionally
// to each payment; the final row reconciles every cent of principal and interest.
export function breakdown(principal:number,total:number,term:number){
 if(!Number.isSafeInteger(principal)||!Number.isSafeInteger(total)||total<principal||principal<=0||!Number.isInteger(term)||term<1||term>120)throw Error('Invalid repayment schedule.');
 let principalPaid=0,interestPaid=0;const interest=total-principal,base=Math.floor(total/term);
 return Array.from({length:term},(_,i)=>{const amount=i===term-1?total-base*i:base;const cumulativeInterest=i===term-1?interest:Math.round(base*(i+1)*interest/total);const interestPart=cumulativeInterest-interestPaid;const principalPart=amount-interestPart;principalPaid+=principalPart;interestPaid=cumulativeInterest;return{number:i+1,principal:principalPart,interest:interestPart,amount,balance:principal-principalPaid}});
}
export function schedule(l:Loan){if(!l.start_date)return[];const base=Math.floor(l.total/l.term);let allocated=l.paid;return Array.from({length:l.term},(_,i)=>{const amount=i===l.term-1?l.total-base*(l.term-1):base;const paid=Math.min(amount,Math.max(0,allocated));allocated-=paid;const start=new Date(l.start_date+'T00:00:00Z');const originalDay=start.getUTCDate();start.setUTCDate(1);start.setUTCMonth(start.getUTCMonth()+i);const lastDay=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate();start.setUTCDate(Math.min(originalDay,lastDay));const date=start.toISOString().slice(0,10);return{number:i+1,date,amount,remaining:amount-paid,status:paid===amount?'Paid':date<new Date().toISOString().slice(0,10)?'Overdue':'Upcoming'}})}
