// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import {sql} from 'drizzle-orm';
import {integer,sqliteTable,text,index,uniqueIndex,primaryKey,type AnySQLiteColumn} from 'drizzle-orm/sqlite-core';
export const members=sqliteTable('members',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),role:text('role').notNull().default('member'),phone:text('phone').notNull().default(''),department:text('department').notNull().default(''),authId:text('auth_id').unique()},t=>[uniqueIndex('members_email_unique').on(sql`lower(trim(${t.email}))`)]);
export const workspace=sqliteTable('workspace',{id:integer('id').primaryKey(),owner:text('owner').notNull()});
export const organization=sqliteTable('organization',{id:integer('id').primaryKey(),name:text('name').notNull(),defaultLateRateBps:integer('default_late_rate_bps').notNull().default(300),revision:integer('revision').notNull().default(0)});
export const orgRoles=sqliteTable('org_roles',{id:text('id').primaryKey(),name:text('name').notNull().unique(),parentId:text('parent_id').references(():AnySQLiteColumn=>orgRoles.id)});
export const memberRoles=sqliteTable('member_roles',{memberId:text('member_id').notNull().references(()=>members.id),roleId:text('role_id').notNull().references(()=>orgRoles.id)},t=>[primaryKey({columns:[t.memberId,t.roleId]})]);
export const loanTypes=sqliteTable('loan_types',{id:text('id').primaryKey(),name:text('name').notNull().unique(),active:integer('active').notNull().default(1)});
export const approvalRoutes=sqliteTable('approval_routes',{typeId:text('type_id').notNull().references(()=>loanTypes.id),position:integer('position').notNull(),roleId:text('role_id').notNull().references(()=>orgRoles.id)},t=>[primaryKey({columns:[t.typeId,t.position]})]);
export const loanApprovals=sqliteTable('loan_approvals',{loanId:text('loan_id').notNull().references(()=>loans.id),position:integer('position').notNull(),roleId:text('role_id').notNull().references(()=>orgRoles.id),roleName:text('role_name').notNull(),status:text('status').notNull().default('pending'),decidedBy:text('decided_by').references(()=>members.id),decidedAt:text('decided_at'),reason:text('reason')},t=>[primaryKey({columns:[t.loanId,t.position]}),index('loan_approvals_role_idx').on(t.roleId,t.loanId)]);
export const loanDocuments=sqliteTable('loan_documents',{loanId:text('loan_id').notNull().references(()=>loans.id),documentId:text('document_id').notNull().unique().references(()=>documents.id)},t=>[primaryKey({columns:[t.loanId,t.documentId]}),index('loan_documents_loan_idx').on(t.loanId)]);
export const loans=sqliteTable('loans',{id:text('id').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),type:text('type').notNull(),amount:integer('amount').notNull(),term:integer('term').notNull(),rate:integer('rate').notNull(),total:integer('total').notNull(),paid:integer('paid').notNull().default(0),status:text('status').notNull().default('pending'),purpose:text('purpose').notNull(),createdAt:text('created_at').notNull(),startDate:text('start_date').notNull().default(''),decisionBy:text('decision_by'),decisionReason:text('decision_reason'),repaymentMethod:text('repayment_method').notNull().default('auto_deduct'),lateWaivers:text('late_waivers').notNull().default('[]'),latePolicy:text('late_policy').notNull().default('[]'),repaymentRevision:integer('repayment_revision').notNull().default(0)},t=>[index('loans_member_idx').on(t.memberId)]);
export const payrollImports=sqliteTable('payroll_imports',{id:text('id').primaryKey(),filename:text('filename').notNull(),recordedBy:text('recorded_by').notNull().references(()=>members.id),createdAt:text('created_at').notNull(),rowCount:integer('row_count').notNull(),total:integer('total').notNull(),skipped:integer('skipped').notNull().default(0)});
export const payments=sqliteTable('payments',{id:text('id').primaryKey(),loanId:text('loan_id').notNull().references(()=>loans.id),amount:integer('amount').notNull(),paidAt:text('paid_at').notNull(),reference:text('reference').notNull(),recordedBy:text('recorded_by').notNull(),interestAmount:integer('interest_amount').notNull().default(0),source:text('source').notNull().default('manual'),importId:text('import_id').references(()=>payrollImports.id),recordedAt:text('recorded_at')},t=>[index('payments_loan_idx').on(t.loanId),uniqueIndex('payments_reference_unique').on(t.reference)]);
export const documents=sqliteTable('documents',{id:text('id').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()},t=>[index('documents_member_idx').on(t.memberId)]);
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),title:text('title').notNull(),body:text('body').notNull(),kind:text('kind').notNull(),read:integer('read').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('notifications_member_idx').on(t.memberId)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),sender:text('sender').notNull().references(()=>members.id),recipient:text('recipient').notNull().references(()=>members.id),body:text('body').notNull(),createdAt:text('created_at').notNull()},t=>[index('messages_sender_idx').on(t.sender),index('messages_recipient_idx').on(t.recipient)]);

export const auditEvents=sqliteTable('audit_events',{id:text('id').primaryKey(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),action:text('action').notNull(),entityId:text('entity_id').notNull(),beforeJson:text('before_json').notNull(),afterJson:text('after_json').notNull(),createdAt:text('created_at').notNull()},t=>[index('audit_events_time_idx').on(t.createdAt,t.id)]);
