// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import {integer,sqliteTable,text,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const members=sqliteTable('members',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),role:text('role').notNull().default('member'),phone:text('phone').notNull().default(''),department:text('department').notNull().default('')});
export const workspace=sqliteTable('workspace',{id:integer('id').primaryKey(),owner:text('owner').notNull()});
export const loans=sqliteTable('loans',{id:text('id').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),type:text('type').notNull(),amount:integer('amount').notNull(),term:integer('term').notNull(),rate:integer('rate').notNull(),total:integer('total').notNull(),paid:integer('paid').notNull().default(0),status:text('status').notNull().default('pending'),purpose:text('purpose').notNull(),createdAt:text('created_at').notNull(),startDate:text('start_date').notNull().default(''),decisionBy:text('decision_by'),decisionReason:text('decision_reason')},t=>[index('loans_member_idx').on(t.memberId)]);
export const payments=sqliteTable('payments',{id:text('id').primaryKey(),loanId:text('loan_id').notNull().references(()=>loans.id),amount:integer('amount').notNull(),paidAt:text('paid_at').notNull(),reference:text('reference').notNull(),recordedBy:text('recorded_by').notNull()},t=>[index('payments_loan_idx').on(t.loanId),uniqueIndex('payments_reference_unique').on(t.reference)]);
export const documents=sqliteTable('documents',{id:text('id').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()},t=>[index('documents_member_idx').on(t.memberId)]);
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),title:text('title').notNull(),body:text('body').notNull(),kind:text('kind').notNull(),read:integer('read').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('notifications_member_idx').on(t.memberId)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),sender:text('sender').notNull().references(()=>members.id),recipient:text('recipient').notNull().references(()=>members.id),body:text('body').notNull(),createdAt:text('created_at').notNull()},t=>[index('messages_sender_idx').on(t.sender),index('messages_recipient_idx').on(t.recipient)]);
